import ProductView from '@/components/ProductView';
import Title from '@/components/Title';
import { Metadata } from 'next';
import React from 'react'
export const metadata: Metadata = {
  title: "Product page",
  description: "Generated by Muhammadumar",
};

export default async function ProductPage() {
  const data = await fetch('https://dummyjson.com/products');
  const products = await data.json();

  return (
    <div className='container mx-auto'>
      <Title title={"Products"} />
      <ProductView data={products?.products} />
    </div>
  );
}