import { Metadata } from 'next';
import React from 'react'
export const metadata: Metadata = {
  title: "Product Detail page",
  description: "Generated by Muhammadumar",
};

const ProductDetail = () => {
  return (
    <div>ProductDetail</div>
  )
}

export default ProductDetail