import type { Metadata } from "next"
import { Card, Avatar, Tag, Divider } from "antd"
import { HeartOutlined, MessageOutlined, CalendarOutlined, UserOutlined } from "@ant-design/icons"

export const metadata: Metadata = {
  title: "Comments Detail Page",
  description: "Generated by Muhammadumar",
}

interface Comment {
  id: number
  body: string
  postId: number
  likes: number
  user: {
    id: number
    username: string
    fullName: string
  }
}

interface Props {
  params: {
    detail: any
  }
}

export default async function CommentsDetail({ params }: { params: Promise<{ detail: string }> }) {
  const { detail } = await params;
  const id = (await params).detail

  try {
    const data = await fetch(`https://dummyjson.com/comments/${id}`)

    if (!data.ok) {
      throw new Error("Comment not found")
    }

    const singleData: Comment = await data.json()

    return (
      <div className="min-h-screen bg-gray-50 py-8">
        <div className="max-w-2xl mx-auto px-4">
          <div className="mb-8">
            <h1 className="text-2xl font-semibold text-gray-900 mb-2">Comment Details</h1>
            <p className="text-gray-600">Comment #{singleData.id}</p>
          </div>

          <Card className="mb-6 shadow-sm border-0">
            <div className="flex items-center gap-4 mb-6">
              <Avatar
                size={48}
                icon={<UserOutlined />}
                className="bg-blue-100"
              />
              <div className="flex-1">
                <h3 className="font-medium text-gray-900 text-lg">{singleData.user.fullName}</h3>
                <p className="text-sm text-gray-500">@{singleData.user.username}</p>
              </div>
              <Tag color="default">ID: {singleData.user.id}</Tag>
            </div>

            <Divider />

            <div className="mb-6">
              <p className="text-gray-800 leading-relaxed text-lg">{singleData.body}</p>
            </div>

            <Divider />

            <div className="flex items-center justify-between text-sm text-gray-500">
              <div className="flex items-center gap-6">
                <div className="flex items-center gap-2">
                  <HeartOutlined />
                  <span>{singleData.likes} likes</span>
                </div>
                <div className="flex items-center gap-2">
                  <MessageOutlined />
                  <span>Post #{singleData.postId}</span>
                </div>
              </div>
              <div className="flex items-center gap-2">
                <CalendarOutlined />
                <span>Comment ID: {singleData.id}</span>
              </div>
            </div>
          </Card>

          <Card className="shadow-sm border-0 bg-blue-50">
            <h4 className="font-medium text-gray-900 mb-4">Comment Information</h4>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm">
              <div>
                <span className="text-gray-500 block">Comment ID:</span>
                <p className="font-medium text-gray-900">{singleData.id}</p>
              </div>
              <div>
                <span className="text-gray-500 block">Post ID:</span>
                <p className="font-medium text-gray-900">{singleData.postId}</p>
              </div>
              <div>
                <span className="text-gray-500 block">User ID:</span>
                <p className="font-medium text-gray-900">{singleData.user.id}</p>
              </div>
            </div>
          </Card>
        </div>
      </div>
    )
  } catch (error) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <Card className="max-w-md mx-auto shadow-sm border-0">
          <div className="text-center py-8">
            <div className="mb-4">
              <MessageOutlined className="text-4xl text-gray-400" />
            </div>
            <h2 className="text-xl font-semibold text-gray-900 mb-2">Comment Not Found</h2>
            <p className="text-gray-600">The comment doesn't exist or has been removed.</p>
          </div>
        </Card>
      </div>
    )
  }
}
