import { Metadata } from 'next';
import React from 'react'
export const metadata: Metadata = {
  title: "Comments Detail Page",
  description: "Generated by Muhammadumar",
};

const CommentsDetail = () => {
  return (
    <div>CommentsDetail</div>
  )
}

export default CommentsDetail