import { Metadata } from 'next';
import React from 'react'
export const metadata: Metadata = {
  title: "Recipes Detail page",
  description: "Generated by Muhammadumar",
};
const RecipesDetail = () => {
  return (
    <div>RecipesDetail</div>
  )
}

export default RecipesDetail