import RecipesView from '@/components/RecipesView'
import Title from '@/components/Title'
import UsersView from '@/components/UsersView'
import { Metadata } from 'next';
import React from 'react'
export const metadata: Metadata = {
  title: "Users page",
  description: "Generated by Muhammadumar",
};

const Users = async () => {
  const data = await fetch('https://dummyjson.com/users')
  const users = await data.json()
  console.log(users);

  return (
    <div>
      <Title title={"Users"} />
      <UsersView data={users?.users} />
    </div>
  )
}

export default Users