import CommentsView from '@/components/CommentsView'
import Title from '@/components/Title'
import { Metadata } from 'next';
import React from 'react'
export const metadata: Metadata = {
  title: "Comments page",
  description: "Generated by Muhammadumar",
};

const Comments = async () => {
  const data = await fetch('https://dummyjson.com/comments')
  const comments = await data.json()
  console.log(comments);

  return (
    <div>
      <Title title={"Comments"} />
      <CommentsView data={comments?.comments} />
    </div>
  )
}

export default Comments