import RecipesView from '@/components/RecipesView'
import Title from '@/components/Title'
import { Metadata } from 'next';
import React from 'react'
export const metadata: Metadata = {
  title: "Recipes page",
  description: "Generated by Muhammadumar",
};

const Recipe = async () => {
  const data = await fetch('https://dummyjson.com/recipes')
  const recipes = await data.json()
  return (
    <div className='container mx-auto'>
      <Title title={"Recipes"} />
      <RecipesView data={recipes?.recipes} />
    </div>
  )
}

export default Recipe