import { Metadata } from 'next';
import React from 'react'
export const metadata: Metadata = {
  title: "Users Detail page",
  description: "Generated by Muhammadumar",
};
const UsersDetail = () => {
  return (
    <div>UsersDetail</div>
  )
}

export default UsersDetail