import type { Metadata } from "next"
import { Card, Tag, Avatar, Divider } from "antd"
import { UserOutlined, MailOutlined, PhoneOutlined, HomeOutlined, BankOutlined, BookOutlined } from "@ant-design/icons"

export const metadata: Metadata = {
  title: "Users Detail page",
  description: "Generated by Muhammadumar",
}

interface User {
  id: number
  firstName: string
  lastName: string
  maidenName: string
  age: number
  gender: string
  email: string
  phone: string
  username: string
  birthDate: string
  image: string
  bloodGroup: string
  height: number
  weight: number
  eyeColor: string
  hair: {
    color: string
    type: string
  }
  address: {
    address: string
    city: string
    state: string
    stateCode: string
    postalCode: string
    country: string
  }
  university: string
  bank: {
    cardType: string
    currency: string
  }
  company: {
    department: string
    name: string
    title: string
  }
  role: string
}

interface Props {
  params: {
    usersDetail: string
  }
}

const UsersDetail = async ({ params }: Props) => {
  const id = await params.usersDetail

  try {
    const data = await fetch(`https://dummyjson.com/users/${id}`)

    if (!data.ok) {
      throw new Error("User not found")
    }

    const user: User = await data.json()

    return (
      <div className="min-h-screen bg-gray-50 py-8">
        <div className="max-w-4xl mx-auto px-4">
          {/* User Profile Header */}
          <Card className="mb-6">
            <div className="flex flex-col md:flex-row items-center gap-6">
              <Avatar size={120} src={user.image} icon={<UserOutlined />} className="bg-blue-100" />
              <div className="text-center md:text-left flex-1">
                <h1 className="text-3xl font-bold text-gray-900 mb-2">
                  {user.firstName} {user.lastName}
                </h1>
                <p className="text-lg text-gray-600 mb-3">@{user.username}</p>
                <div className="flex flex-wrap gap-2 justify-center md:justify-start">
                  <Tag color="blue">{user.role}</Tag>
                  <Tag color="green">{user.gender}</Tag>
                  <Tag color="orange">{user.age} years old</Tag>
                </div>
              </div>
            </div>
          </Card>

          {/* Contact Information */}
          <Card title="Contact Information" className="mb-6">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="flex items-center gap-3">
                <MailOutlined className="text-blue-500" />
                <div>
                  <p className="text-sm text-gray-500">Email</p>
                  <p className="font-medium">{user.email}</p>
                </div>
              </div>
              <div className="flex items-center gap-3">
                <PhoneOutlined className="text-green-500" />
                <div>
                  <p className="text-sm text-gray-500">Phone</p>
                  <p className="font-medium">{user.phone}</p>
                </div>
              </div>
            </div>
          </Card>

          {/* Personal Information */}
          <Card title="Personal Information" className="mb-6">
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              <div>
                <p className="text-sm text-gray-500">Birth Date</p>
                <p className="font-medium">{new Date(user.birthDate).toLocaleDateString()}</p>
              </div>
              <div>
                <p className="text-sm text-gray-500">Blood Group</p>
                <p className="font-medium">{user.bloodGroup}</p>
              </div>
              <div>
                <p className="text-sm text-gray-500">Eye Color</p>
                <p className="font-medium">{user.eyeColor}</p>
              </div>
              <div>
                <p className="text-sm text-gray-500">Height</p>
                <p className="font-medium">{user.height} cm</p>
              </div>
              <div>
                <p className="text-sm text-gray-500">Weight</p>
                <p className="font-medium">{user.weight} kg</p>
              </div>
              <div>
                <p className="text-sm text-gray-500">Hair</p>
                <p className="font-medium">
                  {user.hair.color} {user.hair.type}
                </p>
              </div>
            </div>
          </Card>

          {/* Address */}
          <Card title="Address" className="mb-6">
            <div className="flex items-start gap-3">
              <HomeOutlined className="text-orange-500 mt-1" />
              <div>
                <p className="font-medium">{user.address.address}</p>
                <p className="text-gray-600">
                  {user.address.city}, {user.address.state} {user.address.postalCode}
                </p>
                <p className="text-gray-600">{user.address.country}</p>
              </div>
            </div>
          </Card>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* Work Information */}
            <Card title="Work Information">
              <div className="flex items-start gap-3">
                <BankOutlined className="text-purple-500 mt-1" />
                <div className="space-y-2">
                  <div>
                    <p className="text-sm text-gray-500">Company</p>
                    <p className="font-medium">{user.company.name}</p>
                  </div>
                  <div>
                    <p className="text-sm text-gray-500">Position</p>
                    <p className="font-medium">{user.company.title}</p>
                  </div>
                  <div>
                    <p className="text-sm text-gray-500">Department</p>
                    <p className="font-medium">{user.company.department}</p>
                  </div>
                </div>
              </div>
            </Card>

            {/* Education & Banking */}
            <Card title="Other Information">
              <div className="space-y-4">
                <div className="flex items-center gap-3">
                  <BookOutlined className="text-indigo-500" />
                  <div>
                    <p className="text-sm text-gray-500">University</p>
                    <p className="font-medium">{user.university}</p>
                  </div>
                </div>
                <Divider />
                <div>
                  <p className="text-sm text-gray-500">Banking</p>
                  <p className="font-medium">
                    {user.bank.cardType} - {user.bank.currency}
                  </p>
                </div>
              </div>
            </Card>
          </div>

          {/* User Details */}
          <Card title="User Details" className="mt-6">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div>
                <span className="text-gray-500">User ID:</span>
                <p className="font-medium">{user.id}</p>
              </div>
              <div>
                <span className="text-gray-500">Username:</span>
                <p className="font-medium">{user.username}</p>
              </div>
              <div>
                <span className="text-gray-500">Role:</span>
                <p className="font-medium">{user.role}</p>
              </div>
            </div>
          </Card>
        </div>
      </div>
    )
  } catch (error) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <Card className="max-w-md mx-auto">
          <div className="text-center py-8">
            <UserOutlined className="text-4xl text-gray-400 mb-4" />
            <h2 className="text-xl font-semibold text-gray-900 mb-2">User Not Found</h2>
            <p className="text-gray-600">The user you're looking for doesn't exist.</p>
          </div>
        </Card>
      </div>
    )
  }
}

export default UsersDetail
